version: '3.8'

services:
  srs-ingest:
    build: .
    container_name: srs-ingest
    network_mode: "host"
    restart: always
    command: ./objs/srs -c conf/ingest.conf
    volumes:
      - ./srs-ingest.conf:/usr/local/srs/conf/ingest.conf
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://127.0.0.1:1985/api/v1/versions" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 12G

  backend-go:
    build: ./backend-go
    container_name: backend-go
    network_mode: "host"
    restart: always
    env_file:
      - .env
    depends_on:
      srs-ingest:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
