listen              1935;
max_connections     10000;
srs_log_level       warn;
daemon              off;

# Performance tuning
work_dir            ./objs;
pid                 ./objs/srs.pid;
srs_log_file        ./objs/srs.log;
workers             12;
work_threads        12;

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;
    min_latency     on;

    publish {
        mr          off;
    }

    http_hooks {
        enabled         on;
        on_publish      http://127.0.0.1:3000/api/on_publish;
        on_unpublish    http://127.0.0.1:3000/api/on_unpublish;
    }

    # Forward dinámico gestionado por el Go backend (requerido para usar tokens)
    forward {
        enabled     on;
        backend     http://127.0.0.1:3000/api/on_forward;
    }
}
