listen              1935;
max_connections     10000;
srs_log_level       warn;
srs_log_tank        console;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             /usr/local/srs/objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;

    hls {
        enabled         on;
        hls_fragment    4;
        hls_window      60;
        hls_path        /usr/local/srs/objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_cleanup     on;
        hls_ctx         off;
        hls_ts_ctx      off;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

vhost 37.59.97.144 {
    tcp_nodelay     on;

    hls {
        enabled         on;
        hls_fragment    4;
        hls_window      60;
        hls_path        /usr/local/srs/objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_cleanup     on;
        hls_ctx         off;
        hls_ts_ctx      off;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}