version: '3.8'

services:
  srs-thumbnail:
    build: .
    container_name: iblups-srs-thumbnail
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./srs-thumb.conf:/usr/local/srs/conf/srs.conf:ro
      - srs-data:/usr/local/srs/objs/nginx/html
    cpus: '10.0'
    mem_limit: 10g

  nginx-thumbnail-edge:
    image: nginx:alpine
    container_name: iblups-thumbnail-nginx
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Carpeta compartida donde SRS escribe los thumbnails JPG
      - srs-data:/usr/local/srs/objs/nginx/html:ro
    depends_on:
      - srs-thumbnail
    cpus: '4.0'
    mem_limit: 2g

volumes:
  srs-data:
