server {
    listen 80;
    server_name _;
    
    # Ruta donde la imagen generada por SRS ffmpeg transcode se guarda
    root /usr/local/srs/objs/nginx/html;
    
    # Desactivar logs de acceso para optimizar disco
    access_log off;

    # CORS Headers
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
    
    location / {
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain; charset=utf-8';
            add_header Content-Length 0;
            return 204;
        }
        try_files $uri $uri/ =404;
    }

    # Miniaturas PNG (Sirviendo archivos sin el subdirectorio de la aplicación para evitar bugs de FFmpeg)
    # Ejemplo: /live/jb5.png -> buscará internamente en html/jb5.png
    location /live/ {
        alias /usr/local/srs/objs/nginx/html/;
        
        # Caché corta (5s) para recargar imágenes estáticas convertidas en feed en vivo
        add_header Cache-Control "public, max-age=5, s-maxage=5";
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
    }
}
