server {
    listen 80;
    server_name _;

    root /usr/local/srs/objs/nginx/html;

    access_log off;

    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';

        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain; charset=utf-8';
            add_header Content-Length 0;
            return 204;
        }

        try_files $uri $uri/ =404;
    }

    # Thumbnails PNG
    # Ejemplo: /live/jb5.png -> /usr/local/srs/objs/nginx/html/jb5.png
    location ~ ^/live/(.+\.png)$ {
        alias /usr/local/srs/objs/nginx/html/$1;

        add_header Cache-Control "public, max-age=5, s-maxage=5";
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
    }
}