listen              1935;
max_connections     10000;
srs_log_level       warn;
srs_log_tank        console;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         off;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;

    transcode live {
        enabled     on;
        ffmpeg      /usr/bin/ffmpeg;
        engine snapshot {
            enabled         on;
            iformat         flv;
            vfilter {
                vf fps=1/120,scale=245:142:flags=bilinear;
            }
            vcodec          mjpeg;
            vparams {
                update      1;
                qscale:v    4;
            }
            acodec          an;
            oformat         image2;
            output          ./objs/nginx/html/[stream].jpg;
        }
    }
}