listen              1935;
max_connections     10000;
srs_log_level       trace;
daemon              off;

# Performance tuning para Thumbnailing (alto CPU)
work_dir            ./objs;
pid                 ./objs/srs.pid;
srs_log_file        ./objs/srs.log;
workers             12;
work_threads        12;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         off;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;
    
    # Motor Transcoder para capturar Miniaturas (Thumbnail PNG) usando ffmpeg (integrado con SRS)
    transcode {
        enabled     on;
        ffmpeg      ffmpeg;
        engine snapshot {
            enabled         on;
            vfilter {
                # Toma 1 fotograma cada 10 segundos y escala la imagen a un ancho de 640px (aprox 360p) para ahorrar el máximo de transferencia y cpu.
                vf "fps=1/10,scale=640:-1";
            }
            vcodec          png;
            vparams {
                # Force overwriting the same file without asking prompts. 'update 1' is crucial to keep the same file name constantly updated
                update 1;
            }
            acodec          an;  # No procesar audio
            oformat         image2;
            # Ruta donde se sirve la miniatura. Ej: ./objs/nginx/html/TOKEN.png (La carpeta 'live/' se omite para evitar error de directorio faltante en FFmpeg)
            output          ./objs/nginx/html/[stream].png;
        }
    }
}
